/**
 * HTML renderer for the EDH 32 Deck Challenge.
 * Generates a self-contained HTML file with inline CSS showing
 * challenge progress with commander card art.
 */

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { ChallengeProgress, ColorSlot } from '../domain/deck-organizer.js';
import type { SlotCategory } from '../domain/color-combinations.js';

export interface HTMLRenderOptions {
  outputDir: string;
}

/**
 * Renders the challenge progress as an HTML file and writes it to disk.
 *
 * @param progress - The challenge progress data to render
 * @param options - Rendering options including output directory
 * @returns The file path of the written HTML file
 */
export function renderHTML(progress: ChallengeProgress, options: HTMLRenderOptions): string {
  const content = generateHTMLContent(progress);
  const filename = `${progress.username}-edh-challenge.html`;
  const filepath = join(options.outputDir, filename);
  writeFileSync(filepath, content, 'utf-8');
  return filepath;
}

/**
 * Generates the full HTML content string for the challenge progress.
 *
 * @param progress - The challenge progress data to render
 * @returns Complete self-contained HTML string
 */
export function generateHTMLContent(progress: ChallengeProgress): string {
  const categoryOrder: SlotCategory[] = [
    'colorless',
    'mono',
    'two-color',
    'three-color',
    'four-color',
    'five-color',
  ];

  const categoryLabels: Record<SlotCategory, string> = {
    colorless: 'Colorless',
    mono: 'Mono Color',
    'two-color': 'Two Color (Guilds)',
    'three-color': 'Three Color (Shards & Wedges)',
    'four-color': 'Four Color',
    'five-color': 'Five Color',
  };

  const slotsByCategory = groupSlotsByCategory(progress.slots);

  const sections = categoryOrder
    .map((category) => {
      const slots = slotsByCategory.get(category);
      if (!slots || slots.length === 0) return '';
      return renderCategorySection(category, categoryLabels[category], slots);
    })
    .join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>EDH 32 Deck Challenge - ${escapeHtml(progress.username)}</title>
  <style>
${getInlineCSS()}
  </style>
</head>
<body>
  <header>
    <h1>EDH 32 Deck Challenge</h1>
    <p class="username">${escapeHtml(progress.username)}</p>
    <p class="progress-summary">${progress.filledCount} / ${progress.totalSlots} slots filled</p>
  </header>
  <main>
${sections}
  </main>
  <footer>
    <p>Generated by EDH 32 Deck Challenge Checker</p>
  </footer>
</body>
</html>`;
}

function groupSlotsByCategory(slots: ColorSlot[]): Map<SlotCategory, ColorSlot[]> {
  const map = new Map<SlotCategory, ColorSlot[]>();
  for (const slot of slots) {
    const existing = map.get(slot.category) ?? [];
    existing.push(slot);
    map.set(slot.category, existing);
  }
  return map;
}

function renderCategorySection(category: SlotCategory, label: string, slots: ColorSlot[]): string {
  const slotCards = slots.map((slot) => renderSlotCard(slot)).join('\n');

  return `    <section class="category category-${category}">
      <h2>${escapeHtml(label)}</h2>
      <div class="slots-grid">
${slotCards}
      </div>
    </section>`;
}

function renderSlotCard(slot: ColorSlot): string {
  const isFilled = slot.decks.length > 0;
  const filledClass = isFilled ? 'filled' : 'empty';

  let content: string;
  if (isFilled) {
    const deckEntries = slot.decks
      .map((deck) => {
        const commanders = deck.commanderNames
          .map((name, i) => {
            const imageUrl = deck.commanderImages[i];
            if (imageUrl) {
              return `          <div class="commander">
            <img src="${escapeHtml(imageUrl)}" alt="${escapeHtml(name)}" onerror="this.style.display='none';this.nextElementSibling.style.display='block';" />
            <span class="commander-fallback" style="display:none;">${escapeHtml(name)}</span>
            <span class="commander-name">${escapeHtml(name)}</span>
          </div>`;
            }
            return `          <div class="commander">
            <span class="commander-text-only">${escapeHtml(name)}</span>
          </div>`;
          })
          .join('\n');
        return `        <div class="deck-entry">
          <span class="deck-name">${escapeHtml(deck.deckName)}</span>
${commanders}
        </div>`;
      })
      .join('\n');
    content = deckEntries;
  } else {
    content = `        <div class="empty-label">No deck assigned</div>`;
  }

  const colorsDisplay = slot.colors.length > 0 ? ` (${slot.colors.join('')})` : '';

  return `        <div class="slot-card ${filledClass}">
          <div class="slot-header">
            <span class="slot-name">${escapeHtml(slot.name)}${escapeHtml(colorsDisplay)}</span>
          </div>
          <div class="slot-content">
${content}
          </div>
        </div>`;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function getInlineCSS(): string {
  return `    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background-color: #1a1a2e;
      color: #e0e0e0;
      padding: 2rem;
      min-height: 100vh;
    }

    header {
      text-align: center;
      margin-bottom: 2rem;
    }

    header h1 {
      font-size: 2rem;
      color: #f0c040;
      margin-bottom: 0.5rem;
    }

    .username {
      font-size: 1.2rem;
      color: #a0a0c0;
      margin-bottom: 0.25rem;
    }

    .progress-summary {
      font-size: 1.4rem;
      font-weight: bold;
      color: #60d060;
    }

    main {
      max-width: 1400px;
      margin: 0 auto;
    }

    .category {
      margin-bottom: 2rem;
    }

    .category h2 {
      font-size: 1.3rem;
      color: #c0c0e0;
      border-bottom: 2px solid #333355;
      padding-bottom: 0.5rem;
      margin-bottom: 1rem;
    }

    .slots-grid {
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
      gap: 1rem;
    }

    .slot-card {
      background-color: #2a2a4a;
      border-radius: 8px;
      padding: 1rem;
      border: 2px solid #333355;
      transition: border-color 0.2s;
    }

    .slot-card.filled {
      border-color: #4a6;
    }

    .slot-card.empty {
      border-color: #555;
      opacity: 0.7;
    }

    .slot-header {
      margin-bottom: 0.75rem;
    }

    .slot-name {
      font-weight: bold;
      font-size: 1rem;
      color: #d0d0f0;
    }

    .slot-content {
      display: flex;
      flex-direction: column;
      gap: 0.5rem;
    }

    .deck-entry {
      display: flex;
      flex-direction: column;
      gap: 0.25rem;
    }

    .deck-name {
      font-size: 0.85rem;
      color: #a0a0c0;
      font-style: italic;
    }

    .commander {
      display: flex;
      flex-direction: column;
      align-items: center;
      gap: 0.25rem;
    }

    .commander img {
      width: 100%;
      max-width: 220px;
      border-radius: 10px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.4);
    }

    .commander-name {
      font-size: 0.85rem;
      color: #c0c0e0;
      text-align: center;
    }

    .commander-fallback {
      font-size: 1rem;
      color: #f0c040;
      text-align: center;
      padding: 1rem;
    }

    .commander-text-only {
      font-size: 1rem;
      color: #f0c040;
      text-align: center;
      padding: 1rem;
    }

    .empty-label {
      color: #777;
      font-style: italic;
      text-align: center;
      padding: 2rem 0;
    }

    footer {
      text-align: center;
      margin-top: 3rem;
      padding-top: 1rem;
      border-top: 1px solid #333355;
      color: #666;
      font-size: 0.85rem;
    }`;
}
